name: Build

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: build profile
        options: 
        - build
        - Build_Push
      repo:
        required: false
      image_name:
        required: true        
        default: 'pass-words'
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build
      run: |
        TIMESTAMP=$(date +%s)
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:${TIMESTAMP} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:${TIMESTAMP}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}:latest


  
